sudo: required
dist: trusty
language: node_js
node_js: '8'
branches:
  only:
  - master

before_install:
  - openssl aes-256-cbc -K $encrypted_a8f668d603d4_key -iv $encrypted_a8f668d603d4_iv -in keys/deploy.enc -out keys/deploy -d
  - chmod 600 keys/deploy

script: sh build.sh